### PR TITLE
inOutLinear

### PR DESCRIPTION
**Pull request by HeySora**
inOutLinear

### CODE REVIEW

**Comment by DPS2004** [comment]
inOutLinear

**Comment by XeroOl** [comment]
if you also could add inLinear and outLinear and outInLinear that would be awesome

**Comment by HeySora** [comment]
> if you also could add inLinear and outLinear and outInLinear that would be awesome

@XeroOl done

**Comment by XeroOl** [comment]
inOutLinear

**Comment by XeroOl** [comment]
Sorry it got reverted, you'll have to try again

**Pull request merged**
